"use client";

import { useState, useRef, useEffect } from "react";
import "katex/dist/katex.min.css";
import katex from "katex";
import { toast, Toaster } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { 
  FileText, 
  Upload, 
  Loader2, 
  CheckCircle2, 
  Image as ImageIcon, 
  Copy, 
  Download, 
  Sparkles, 
  FileUp,
  BrainCircuit,
  Trash2
} from "lucide-react";
import { cn } from "@/lib/utils";

function MathText({ text }: { text: string }) {
  if (!text) return null;
  
  // Split by inline math $...$
  const parts = text.split(/(\$.*?\$)/g);
  
  return (
    <span>
      {parts.map((part, i) => {
        if (part.startsWith('$') && part.endsWith('$')) {
          const math = part.slice(1, -1);
          try {
            const html = katex.renderToString(math, { throwOnError: false, displayMode: false });
            return <span key={i} dangerouslySetInnerHTML={{ __html: html }} />;
          } catch (e) {
            return <span key={i}>{part}</span>;
          }
        }
        return <span key={i}>{part}</span>;
      })}
    </span>
  );
}

export default function Home() {
  const [file, setFile] = useState<File | null>(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);
  const [dragActive, setDragActive] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleUpload = async () => {
    if (!file) return;
    setLoading(true);
    const formData = new FormData();
    formData.append("file", file);

    try {
      const response = await fetch("/api/convert", { method: "POST", body: formData });
      
      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(errorText || "Gagal menghubungi server");
      }

      const data = await response.json();
      
      if (data.status === "success") {
        setResult(data.data);
      } else {
        throw new Error(data.detail || "Gagal konversi ke JSON");
      }
    } catch (e: any) { 
      console.error(e);
      alert(`Gagal konversi: ${e.message}`); 
    } finally { 
      setLoading(false); 
    }
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setFile(e.target.files[0]);
    }
  };

  const onDrag = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") {
      setDragActive(true);
    } else if (e.type === "dragleave") {
      setDragActive(false);
    }
  };

  const onDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      setFile(e.dataTransfer.files[0]);
    }
  };

  const clearFile = () => {
    setFile(null);
    setResult(null);
  };

  const [templateId, setTemplateId] = useState<string>("");

  const copyToClipboard = () => {
    if (!result) return;
    navigator.clipboard.writeText(JSON.stringify(result, null, 2));
    toast.success("Salinan berhasil ditaruh di clipboard!");
  };

  const downloadJson = () => {
    if (!result) return;
    const blob = new Blob([JSON.stringify(result, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${result.metadata?.document_title || "form-result"}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const generateGoogleFormScript = () => {
    if (!result) return;
    
    const isTemplateMode = templateId.trim() !== "";
    const finalFormId = templateId.trim();

    const scriptTemplate = `/**
 * GOOGLE APPS SCRIPT: AUTO-GENERATED BY AI FORM BUILDER
 * 1. Buka script.google.com
 * 2. Buat Project Baru
 * 3. Hapus kode lama, tempel kode ini
 * 4. Klik 'Run' (Jalankan)
 */

function processFormAI() {
  const data = ${JSON.stringify(result, null, 2)};
  let form;

  ${isTemplateMode ? `
  // MODE: UPDATE TEMPLATE
  try {
    form = FormApp.openById("${finalFormId}");
    form.addPageBreakItem().setTitle(data?.metadata?.document_title || "Daftar Soal Baru");
  } catch(e) {
    throw new Error("Gagal membuka Form! Pastikan ID Form benar dan Anda memiliki akses edit.");
  }
  ` : `
  // MODE: BUAT BARU
  form = FormApp.create(data?.metadata?.document_title || "Digital Form Result");
  form.setDescription(
    "Mata Pelajaran: " + (data?.metadata?.subject || "-") + "\\n" +
    "Penyusun: " + (data?.metadata?.author || "-") + "\\n" +
    "Generated by AI Form Builder"
  );
  `}

  // Ubah menjadi Kuis agar Kunci Jawaban & Poin aktif
  form.setIsQuiz(true);

  const items = data.items || data.questions || [];

  items.forEach((item, index) => {
    try {
      const type = item.type || "essay"; // Default ke essay jika AI gagal mendeteksi
      
      // Mengatasi AI yang sering halusinasi nama kunci (key) JSON
      let rawText = item.text || item.question_text || item.question || "";
      
      // Jika teks benar-benar kosong tapi ada gambar
      if (rawText.trim() === "" && item.image_context_hint) {
        rawText = "[Rujukan Visual]: " + item.image_context_hint;
      }
      
      // Jika masill kosong, beri penamaan default agar Google Script tidak error
      if (rawText.trim() === "") {
        rawText = "Teks tidak terbaca oleh AI";
      }
      
      // Tambahkan nomor urut dan kategori
      const text = (index + 1) + ". " + rawText + (item.category ? " [" + item.category + "]" : "");
      
      // Cek Kunci Jawaban
      const rawAns = item.answer_key ? item.answer_key.toString().toLowerCase() : "";
      
      if (type === "multiple_choice") {
        const mc = form.addMultipleChoiceItem().setTitle(text).setPoints(1);
        if (item.options && typeof item.options === 'object') {
          const choices = Object.entries(item.options)
            .filter(([k, v]) => v !== null && v.toString().trim() !== "")
            .map(([k, v]) => {
              const isCorrect = rawAns === k.toLowerCase();
              return mc.createChoice(v.toString(), isCorrect);
            });
          if (choices.length > 0) mc.setChoices(choices);
        }
      } 
      else if (type === "checkbox") {
        const cb = form.addCheckboxItem().setTitle(text).setPoints(2);
        if (item.options && typeof item.options === 'object') {
          const choices = Object.entries(item.options)
            .filter(([k, v]) => v !== null && v.toString().trim() !== "")
            .map(([k, v]) => {
              // Untuk checkbox, answer key bisa berupa koma (e.g. "B, C")
              const isCorrect = rawAns.includes(k.toLowerCase());
              return cb.createChoice(v.toString(), isCorrect);
            });
          if (choices.length > 0) cb.setChoices(choices);
        }
      } 
      else {
        // Fallback untuk essay dan curriculum_objective (atau apa pun yang tak terduga)
        form.addParagraphTextItem().setTitle(text).setPoints(5);
      }
    } catch (e) {
      Logger.log("Error pada item ke-" + (index+1) + ": " + e.message);
    }
  });

  Logger.log("SELESAI! Form Anda: " + form.getEditUrl());
}`;

    const blob = new Blob([scriptTemplate], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = isTemplateMode ? `Update_Template_Script.txt` : `Create_New_Form_Script.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success(isTemplateMode ? "Skrip UPDATE berhasil diunduh!" : "Skrip FORM BARU berhasil diunduh!");
  };

  return (
    <div className="min-h-screen bg-[#f8fafc] text-slate-900 font-sans selection:bg-blue-100 uppercase-none">
      <Toaster position="top-center" richColors />
      {/* Background Ornaments */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none z-0">
        <div className="absolute -top-[10%] -left-[10%] w-[40%] h-[40%] bg-blue-100/50 rounded-full blur-[120px]" />
        <div className="absolute top-[20%] -right-[10%] w-[30%] h-[30%] bg-indigo-100/50 rounded-full blur-[100px]" />
      </div>

      <div className="relative z-10 max-w-5xl mx-auto px-4 py-12 md:py-20 lg:py-24 space-y-12">
        {/* Header Section */}
        <header className="text-center space-y-5 max-w-3xl mx-auto">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-emerald-50 border border-emerald-100 text-emerald-700 text-sm font-semibold shadow-sm">
            <Sparkles size={16} />
            Asisten Pintar Guru Indonesia
          </div>
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight text-slate-800 leading-tight">
            Ubah Soal Word Menjadi <br/>
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-600 to-teal-500">Google Form Otomatis</span>
          </h1>
          <div className="mt-4 space-y-1">
            <p className="text-sm font-medium text-emerald-600 tracking-wide">
              Dibuat Oleh:{" "}
              <a 
                href="https://fahri-zanuar-pradian-portofolio.vercel.app/" 
                target="_blank" 
                rel="noopener noreferrer"
                className="underline underline-offset-2 hover:text-emerald-800 transition-colors font-bold"
              >
                Fahri Zanuar Pradian
              </a>
            </p>
            <p className="text-sm text-slate-500">
              Hubungi saya dengan meng-klik nama di atas untuk pembuatan aplikasi berbasis AI, sistem web cerdas, atau kolaborasi proyek IT lainnya!
            </p>
          </div>
          <p className="text-xl text-slate-700 max-w-2xl mx-auto leading-relaxed pt-2">
            Tidak perlu copy-paste satu per satu. Unggah file Word Bapak/Ibu, dan biarkan sistem membuatkan Google Form-nya.
          </p>
        </header>

        {/* Instructions for Teachers */}
        <div className="bg-white rounded-2xl shadow-md border-t-4 border-t-emerald-500 border-slate-200 p-8 max-w-3xl mx-auto">
          <h3 className="text-2xl font-extrabold text-slate-800 mb-6 border-b border-slate-100 pb-4">Cara Penggunaan (Sangat Mudah):</h3>
          <div className="flex flex-col gap-6">
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 rounded-full bg-emerald-100 text-emerald-700 flex items-center justify-center font-bold text-xl shrink-0 mt-1">1</div>
              <div>
                <p className="font-bold text-lg text-slate-800">Unggah File Soal</p>
                <p className="text-base text-slate-600 mt-1">Siapkan file soal Bapak/Ibu dalam format Word (.docx) lalu masukkan ke dalam kotak unggah di bawah ini, kemudian klik tombol "Proses Sekarang".</p>
              </div>
            </div>
            
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 rounded-full bg-emerald-100 text-emerald-700 flex items-center justify-center font-bold text-xl shrink-0 mt-1">2</div>
              <div>
                <p className="font-bold text-lg text-slate-800">Cek Hasil Ekstraksi AI</p>
                <p className="text-base text-slate-600 mt-1">Sistem akan secara cerdas membaca soal (Pilgan maupun Esai). Pastikan soal-soal tersebut sudah terbaca dengan rapi di layar.</p>
              </div>
            </div>

            <div className="flex items-start gap-4">
              <div className="w-10 h-10 rounded-full bg-emerald-100 text-emerald-700 flex items-center justify-center font-bold text-xl shrink-0 mt-1">3</div>
              <div>
                <p className="font-bold text-lg text-slate-800">Jadikan Google Form</p>
                <p className="text-base text-slate-600 mt-1">Punya template Gform sekolah? Masukkan "ID Form" dari alamat browser Bapak/Ibu. Klik "Unduh Skrip", lalu tempel ke <strong>script.google.com</strong> dan klik jalankan (Run).</p>
              </div>
            </div>
          </div>
        </div>

        {/* Main Interface */}
        <div className="grid grid-cols-1 gap-8 max-w-2xl mx-auto">
          <Card className="border-none shadow-[0_8px_30px_rgb(0,0,0,0.06)] bg-white/80 backdrop-blur-sm overflow-hidden transition-all">
            <CardHeader className="pb-4 border-b border-slate-50">
              <CardTitle className="text-xl flex items-center gap-2 text-slate-800">
                <FileText className="text-blue-600" /> Area Unggah File
              </CardTitle>
              <CardDescription>Format yang didukung: .docx (Microsoft Word)</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              {/* Drag and Drop Zone */}
              <div 
                className={cn(
                  "relative group cursor-pointer border-2 border-dashed rounded-xl p-8 transition-all duration-300 flex flex-col items-center justify-center space-y-4",
                  dragActive ? "border-blue-500 bg-blue-50/50" : "border-slate-200 hover:border-slate-300 hover:bg-slate-50/50",
                  file ? "bg-green-50/30 border-green-200" : ""
                )}
                onDragEnter={onDrag}
                onDragLeave={onDrag}
                onDragOver={onDrag}
                onDrop={onDrop}
                onClick={() => fileInputRef.current?.click()}
              >
                <Input 
                  ref={fileInputRef}
                  type="file" 
                  accept=".docx" 
                  className="hidden" 
                  onChange={handleFileChange} 
                />
                
                <div className={cn(
                  "w-16 h-16 rounded-2xl flex items-center justify-center transition-transform group-hover:scale-110 duration-300",
                  file ? "bg-green-100 text-green-600" : "bg-blue-50 text-blue-600"
                )}>
                  {file ? <CheckCircle2 size={32} /> : <Upload size={32} />}
                </div>

                <div className="text-center">
                  <p className="font-semibold text-slate-700">
                    {file ? file.name : "Klik untuk pilih atau drag file ke sini"}
                  </p>
                  <p className="text-sm text-slate-400 mt-1">
                    {file ? `${(file.size / 1024).toFixed(1)} KB` : "Pastikan dokumen berisi teks/tabel yang ingin dikonversi"}
                  </p>
                </div>

                {file && (
                  <button 
                    onClick={(e) => { e.stopPropagation(); clearFile(); }}
                    className="absolute top-4 right-4 p-2 text-slate-400 hover:text-red-500 transition-colors"
                  >
                    <Trash2 size={18} />
                  </button>
                )}
              </div>

              <div className="flex gap-3">
                <Button 
                  onClick={handleUpload} 
                  disabled={loading || !file} 
                  className="flex-1 bg-blue-600 hover:bg-blue-700 text-white shadow-lg shadow-blue-200 h-12 text-base font-medium rounded-xl transition-all active:scale-95"
                >
                  {loading ? (
                    <>
                      <Loader2 className="mr-3 animate-spin" /> 
                      Menganalisis Dokumen...
                    </>
                  ) : (
                    <>
                      <BrainCircuit className="mr-3" /> 
                      Proses Sekarang
                    </>
                  )}
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Results Section */}
        {loading && !result && (
          <div className="max-w-4xl mx-auto space-y-4 animate-pulse">
            <div className="h-10 w-48 bg-slate-200 rounded-lg mx-auto" />
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {[1, 2, 3, 4].map(idx => (
                <div key={idx} className="h-48 bg-slate-100 rounded-xl" />
              ))}
            </div>
          </div>
        )}

        {result && (
          <div className="space-y-8">
            {/* Result Header & Actions */}
            <div className="flex flex-col md:flex-row md:items-start justify-between gap-6 pb-8 border-b border-slate-200">
              <div className="flex items-start gap-5">
                <div className="w-14 h-14 bg-green-100 text-green-600 rounded-2xl flex items-center justify-center shrink-0 shadow-sm">
                  <CheckCircle2 size={28} />
                </div>
                <div className="space-y-1">
                  <h2 className="text-3xl font-extrabold text-slate-900 tracking-tight">
                    {result.metadata?.document_title || "Hasil Ekstraksi"}
                  </h2>
                  <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-slate-500 text-sm font-medium">
                    {result.metadata?.subject && <span className="flex items-center gap-1"><Sparkles size={14} className="text-blue-500" /> {result.metadata.subject}</span>}
                    {result.metadata?.author && <span>• Penyusun: {result.metadata.author}</span>}
                    {result.metadata?.school && <span>• {result.metadata.school}</span>}
                  </div>
                  <p className="text-indigo-600 font-semibold text-sm pt-1">
                    Tipe: {result.content_type === "exam_paper" ? "Lembar Soal" : "Dokumen Kurikulum"} • {result.items?.length || 0} Item Terdeteksi
                  </p>
                </div>
              </div>
              <div className="flex flex-col md:flex-row items-end gap-4 bg-slate-50 p-5 rounded-2xl border border-slate-200">
                <div className="flex flex-col gap-2 flex-1 w-full">
                  <label className="text-sm font-bold text-slate-700">Punya Template Form Berisi Token/Identitas?</label>
                  <p className="text-xs text-slate-500 mb-1">Jika Bapak/Ibu sudah punya form dan mau menambahkan soal ini ke form tersebut, masukkan ID Form-nya di bawah ini. Jika dikosongkan, sistem akan membuat Form Baru secara acak.</p>
                  <Input 
                    placeholder="Contoh ID Form: 1A2B3C4D..." 
                    value={templateId}
                    onChange={(e) => setTemplateId(e.target.value)}
                    className="h-12 rounded-xl border-slate-300 bg-white text-base focus:bg-white transition-all shadow-inner"
                  />
                </div>
                <div className="flex items-end h-full w-full md:w-auto">
                  <Button className="w-full h-12 px-6 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white shadow-lg shadow-emerald-200 transition-all font-bold text-base" onClick={generateGoogleFormScript}>
                    <FileText className="mr-2" size={20} /> Unduh Skrip Google Form
                  </Button>
                </div>
              </div>
              
              <div className="flex justify-end pt-2 gap-3">
                <Button variant="ghost" className="text-slate-500 hover:text-slate-700 hover:bg-slate-100" onClick={copyToClipboard}>
                  <Copy className="mr-2" size={16} /> Salin Data Mentah
                </Button>
                <Button variant="ghost" className="text-slate-500 hover:text-slate-700 hover:bg-slate-100" onClick={downloadJson}>
                  <Download className="mr-2" size={16} /> Unduh Data Mentah
                </Button>
              </div>
            </div>
            
            {/* Questions/Items Grid */}
            <div className="grid grid-cols-1 gap-6">
              {result.items?.map((item: any, idx: number) => (
                <Card key={idx} className="border-none shadow-[0_4px_20px_rgb(0,0,0,0.03)] bg-white overflow-hidden group hover:shadow-[0_4px_25px_rgb(0,0,0,0.06)] transition-all">
                  <CardContent className="p-0 flex">
                    <div className={cn(
                      "w-1.5 h-auto transition-colors",
                      item.type === 'curriculum_objective' ? "bg-emerald-500" : "bg-blue-500 group-hover:bg-indigo-500"
                    )} />
                    <div className="p-8 space-y-6 flex-1">
                      <div className="flex flex-col md:flex-row md:items-start justify-between gap-4">
                        <div className="space-y-3">
                          <div className="flex flex-wrap items-center gap-2">
                            <span className={cn(
                              "inline-block px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider",
                              item.type === 'curriculum_objective' ? "bg-emerald-50 text-emerald-700 border border-emerald-100" : "bg-blue-50 text-blue-700 border border-blue-100"
                            )}>
                              {item.type?.replace('_', ' ')}
                            </span>
                            {item.category && (
                              <span className="text-[11px] font-semibold text-slate-400 bg-slate-50 px-2.5 py-0.5 rounded-full border border-slate-100">
                                {item.category}
                              </span>
                            )}
                          </div>
                          <div className="font-semibold text-lg text-slate-800 leading-snug">
                            <span className="text-slate-400 mr-2">#{item.id || idx + 1}</span>
                            <MathText text={item.text} />
                          </div>
                        </div>
                        
                        {item.answer_key && (
                          <div className="shrink-0 bg-green-50 text-green-700 text-xs font-bold px-3 py-1.5 rounded-lg border border-green-100 self-start">
                            Kunci: {item.answer_key}
                          </div>
                        )}
                      </div>
                      
                      {item.has_image && (
                        <div className="bg-slate-50 p-8 rounded-2xl border-2 border-dashed border-slate-200 flex flex-col items-center text-slate-400">
                          <ImageIcon size={40} strokeWidth={1.5} />
                          <p className="text-sm font-medium mt-3 text-center">
                            Rujukan Visual: <span className="text-slate-600">{item.image_context_hint}</span>
                          </p>
                        </div>
                      )}

                      {item.options ? (
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                          {Object.entries(item.options).map(([key, val]: any) => (
                            <div key={key} className="group/opt flex items-center gap-4 p-4 border border-slate-100 rounded-xl hover:border-blue-200 hover:bg-blue-50/30 transition-all">
                              <div className="flex items-center justify-center w-8 h-8 rounded-lg bg-slate-100 group-hover/opt:bg-blue-100 group-hover/opt:text-blue-600 text-slate-500 text-sm font-bold transition-colors uppercase">
                                {key}
                              </div>
                              <span className="text-slate-700 font-medium tracking-tight">
                                <MathText text={val} />
                              </span>
                            </div>
                          ))}
                        </div>
                      ) : (
                        item.type !== 'curriculum_objective' && (
                          <div className="bg-slate-50/50 p-4 border border-slate-100 rounded-xl">
                            <p className="text-slate-400 italic text-sm">
                              Item ini tidak memiliki pilihan jawaban (Esai/Instruksi).
                            </p>
                          </div>
                        )
                      )}

                      {item.metadata_extra && (Object.values(item.metadata_extra).some(v => v)) && (
                        <div className="pt-4 mt-4 border-t border-slate-100 flex flex-wrap gap-4">
                          {item.metadata_extra.profil_pancasila && (
                            <div className="text-[11px] text-slate-500">
                              <span className="font-bold text-slate-700">Profil Pancasila:</span> {item.metadata_extra.profil_pancasila}
                            </div>
                          )}
                          {item.metadata_extra.jp_allocation && (
                            <div className="text-[11px] text-slate-500">
                              <span className="font-bold text-slate-700">Alokasi JP:</span> {item.metadata_extra.jp_allocation}
                            </div>
                          )}
                        </div>
                      )}
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>

            <div className="text-center py-12 border-t border-slate-200 mt-20">
              <p className="text-slate-400 text-sm italic">
                Sistem menggunakan algoritma AI untuk melakukan verifikasi struktur data dokumen akademik Indonesia.
              </p>
            </div>
          </div>
        )}
        
        {/* Video Tutorial Section - Rendered regardless of result */}
        <div className="max-w-3xl mx-auto mt-16 pb-12">
          <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
            <div className="p-6 text-center border-b border-slate-100 bg-slate-50">
              <h3 className="text-xl font-bold text-slate-800">Panduan Video Tutorial</h3>
              <p className="text-sm text-slate-500 mt-1">Tonton video singkat berikut untuk panduan langkah demi langkah</p>
            </div>
            <div className="relative w-full pb-[56.25%]">
              <iframe 
                className="absolute top-0 left-0 w-full h-full"
                src="https://www.youtube.com/embed/a9wpgyKKFuA" 
                title="Panduan Penggunaan Word to Form AI" 
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
                allowFullScreen
              ></iframe>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}